name: Build on Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      
      - name: Install dependencies
        run: scripts/install-dependencies.sh

      - name: Create build directory
        run: mkdir build

      - name: Run CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

      - name: Build
        run: cmake --build build --config Release
